services:
  client-dev:
    container_name: kokomen-client
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install --immutable && yarn client:dev"
    environment:
      - NODE_ENV=development

  storybook:
    container_name: kokomen-ui
    image: node:18-alpine
    ports:
      - "6006:6006"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install --immutable && yarn ui:dev"
    environment:
      - NODE_ENV=development
