services:
  client-dev:
    container_name: kokomen-client
    image: node:18
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install --immutable && yarn client:dev"
    environment:
      - NODE_ENV=development

  storybook:
    container_name: kokomen-ui
    image: node:18
    ports:
      - "6006:6006"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: sh -c "yarn install --immutable && yarn ui:dev"
  nginx:
    container_name: kokomen-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client-dev
